# DVC Pipeline for EEG MI Classification
# Run: dvc repro

stages:
  train:
    cmd: python scripts/train.py training.logging.use_mlflow=true
    deps:
      - scripts/train.py
      - src/models/custom.py
      - src/training/trainer.py
      - src/data/moabb_loader.py
      - config/config.yaml
      - config/model/custom.yaml
      - config/training/default.yaml
      - config/data/default.yaml
    outs:
      - models/best_model.pt
      - models/last_model.pt

  tune:
    cmd: python scripts/tune.py --n-trials 30
    deps:
      - scripts/tune.py
      - src/models/custom.py
      - src/training/trainer.py
      - config/config.yaml
      - config/model/custom.yaml
      - config/training/default.yaml
